#!/bin/bash

#-------------------------------------------------------------------------
# list all blocks
#-------------------------------------------------------------------------
declare -a blocks=(
  "alert_handler"
  "aes"
  "gpio"
  "flash_ctrl"
  "hmac"
  "otp_ctrl"
  "pwrmgr"
  "rv_core_ibex"
  "rv_dm"
  "rv_timer"
  "spi_device"
  "uart"
  "usbdev"
  "usbuart"
  #"top_earlgrey"
  # run formal on dedicated FPV testbenches
  "prim_arbiter_ppc_fpv"
  "prim_arbiter_tree_fpv"
  "prim_arbiter_fixed_fpv"
  "prim_alert_rxtx_fpv"
  "prim_alert_rxtx_fatal_fpv"
  "prim_alert_rxtx_async_fpv"
  "prim_alert_rxtx_async_fatal_fpv"
  "prim_esc_rxtx_fpv"
  "prim_lfsr_fpv"
  "prim_fifo_sync_fpv"
  "prim_packer_fpv"
  "prim_secded_22_16_fpv"
  "prim_secded_28_22_fpv"
  "prim_secded_39_32_fpv"
  "prim_secded_72_64_fpv"
  "prim_secded_hamming_22_16_fpv"
  "prim_secded_hamming_39_32_fpv"
  "prim_secded_hamming_72_64_fpv"
  "pinmux_fpv"
  "rv_plic_fpv"
  "rv_plic_generic_fpv"
  "alert_handler_esc_timer_fpv"
  "alert_handler_ping_timer_fpv"
)

#-------------------------------------------------------------------------
